### ISSUE TITLE
Create option for user to choose between 2 different color schemes

### ISSUE THREAD

**Issue by ksommer98** [asktheaxis/musicTable#17]
2 color schemes have been created: light version and dark version. Create an option where the user can choose which scheme they want (personalizing).

**Comment by RobRuwe** [comment]
We are going to implement some kind of user accounts and preferences, and these changes will apply there

**Comment by ksommer98** [comment]
Created attributes and 2 themes using those attributes (light theme and dark theme). Will later use these themes to create the option for users to toggle between the 2 color themes.
